---
- name: Create directory tree for user
  include_tasks: directory_structure.yml

- name: Include ssh setup
  import_tasks: firewall.yml

- name: Install flatpak apps
  import_tasks: flatpak.yml

- name: Import rpm related dev tools
  import_tasks: rpm.yml
  tags:
    - rpm
    - development_tools

- name: Setup time and ntp
  import_tasks: time.yml

- name: Setup tmux
  import_tasks: tmux.yml
