---
- name: Play the one timers as root for system-wide changes
  hosts: localhost
  become: true
  become_user: nikromen

  vars_files:
    - group_vars/all
    - group_vars/directory_structure
    - group_vars/flatpak_apps

  roles:
    - role: one_timers
